version: '2'
services:
  toolbox:
    image: alpine
    container_name: toolbox
    restart: always
    ports:
      - 8089:8089
    volumes:
      - ../server:/opt/toolbox/server
      - ../config.yaml:/opt/toolbox/config.yaml
      - ../data.db:/opt/toolbox/data.db
      - ../assets:/opt/toolbox/assets
    working_dir: /opt/toolbox
    command:
      ["./server"]

